# Generated by Django 6.0.4 on 2026-04-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Название опроса"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликован"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="own_polls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец опроса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опрос",
                "verbose_name_plural": "Опросы",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата начала"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="polls.poll",
                        verbose_name="Опрос",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "db_table": "polls_poll_runs",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "order",
                    models.PositiveSmallIntegerField(verbose_name="Порядок вопроса"),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="polls.poll",
                        verbose_name="Опрос",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Текст варианта ответа"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(verbose_name="Порядок варианта ответа"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="polls.question",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_text",
                    models.TextField(
                        blank=True, verbose_name="Текст пользовательского ответа"
                    ),
                ),
                (
                    "poll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="polls.pollrun",
                        verbose_name="Проходимый опрос",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="polls.question",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_in_answers",
                        to="polls.choice",
                        verbose_name="Выбранный вариант ответа",
                    ),
                ),
            ],
            options={
                "db_table": "polls_question_answers",
            },
        ),
        migrations.AddIndex(
            model_name="pollrun",
            index=models.Index(
                fields=["poll", "user"], name="polls_poll__poll_id_daf802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollrun",
            index=models.Index(
                fields=["poll", "completed_at"], name="polls_poll__poll_id_cb9a9a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pollrun",
            constraint=models.UniqueConstraint(
                fields=("poll", "user"), name="unique_poll_user"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["poll", "order"], name="polls_quest_poll_id_f9faa2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("poll", "order"), name="unique_poll_order"
            ),
        ),
        migrations.AddIndex(
            model_name="choice",
            index=models.Index(
                fields=["question", "order"], name="polls_choic_questio_b72825_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_question_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionanswer",
            constraint=models.UniqueConstraint(
                fields=("poll_run", "question"), name="unique_poll_run_question"
            ),
        ),
    ]
